Copilot実行前のコミット

diff --git a/common/master b/common/master
--- a/common/master
+++ b/common/master
@@ -4,6 +4,7 @@
 . [[[SERVICE_LIB_DIR]]]/FUNC_BUILD
 . [[[SERVICE_LIB_DIR]]]/FUNC_COMMON
 . [[[SERVICE_LIB_DIR]]]/FUNC_REMOVE
+DMNG_JSON="[[[SERVICE_LIB_DIR]]]/dmng.json"
 
 execute_file_path="$(cd $(dirname $0) && pwd)/$(basename $0)"
 execute_paramator="$@"
@@ -16,6 +17,12 @@ elif [ "${user_check_result}" -eq 1 ]; then
 	exit 1
 fi
 
+DMNG_JSON_STR=$(cat "${DMNG_JSON}")
+if [ -z "${DMNG_JSON_STR}" ]; then
+	echo "Error: Failed to read dmng.json. Please check the file content."
+	exit 1
+fi
+
 case "${1}" in
 	#TODO:BACKUPを作る
 	build)
@@ -23,30 +30,38 @@ case "${1}" in
 	;;
 	#TODO:COMMANDを作る
 	disable)
-		sed -i "" -e "/${MINECRAFT_SERVER_SERVICE_NAME}_enable=/d" /etc/rc.conf
+		EXECUTE_COMMAND=$(get_daemon_json_value "disable" ${DMNG_JSON_STR})
 	;;
 	enable)
-		echo "${MINECRAFT_SERVER_SERVICE_NAME}_enable=\"YES\"" >> /etc/rc.conf
+		EXECUTE_COMMAND=$(get_daemon_json_value "enable" ${DMNG_JSON_STR})
 	;;
 	remove)
 		FUNC_REMOVE
+		exit ${?}
 	;;
 	restart)
-		service "${MINECRAFT_SERVER_SERVICE_NAME}" stop
-		service "${MINECRAFT_SERVER_SERVICE_NAME}" start
+		EXECUTE_COMMAND=$(get_daemon_json_value "restart" ${DMNG_JSON_STR})
 	;;
 	#TODO:SNAPSHOTを作る
 	start)
-		service "${MINECRAFT_SERVER_SERVICE_NAME}" start
+		EXECUTE_COMMAND=$(get_daemon_json_value "start" ${DMNG_JSON_STR})
 	;;
 	status)
-		service "${MINECRAFT_SERVER_SERVICE_NAME}" status
+		EXECUTE_COMMAND=$(get_daemon_json_value "status" ${DMNG_JSON_STR})
 	;;
 	stop)
-		service "${MINECRAFT_SERVER_SERVICE_NAME}" stop
+		EXECUTE_COMMAND=$(get_daemon_json_value "stop" ${DMNG_JSON_STR})
 	;;
 	*)
 	echo "Usage: ${0} {build|disable|enable|restart|start|stop}"
 	exit 1
 esac
-exit 0
+
+if [ -z "${EXECUTE_COMMAND}" ]; then
+	echo "Error: Failed to read command from dmng.json. Please check the file content."
+	exit 1
+fi
+
+eval "${EXECUTE_COMMAND}"
+
+exit ${?}
